### ISSUE TITLE
Add PwdHash to F-Droid

### ISSUE THREAD

**Issue by quassy** [phw/Android-PwdHash#12]
As your app is BSD licensed and thus Open Source it would be great if it could also be published to F-Droid.

(Thanks for your work btw!)

**Comment by phw** [comment]
It already should be since a long time :):

https://f-droid.org/packages/com.uploadedlobster.PwdHash/

**Comment by quassy** [comment]
Good to know. Weirdly enough I can't find it when searching in the F-Droid app (keywords like "PwdHash", "Password Hash" or even "Password" won't show it), is PwdHash limited to certain recent Android version? 

Testing with a Samsung Galaxy S4 (GT-I9505), Android 5.0.1 (unrooted), F-Droid 0.102.3 (most recent version you can get from the website).

**Comment by phw** [comment]
Indeed, I can't install it via fdroid either. Might be related to the Disabled algorithm warning on https://f-droid.org/wiki/page/com.uploadedlobster.PwdHash

In general I currently cannot recommend to use the pwdhash algorithm for your passwords. There have been successful brute Force attacks, see https://www.google.de/url?sa=t&source=web&rct=j&url=http://www.flypig.co.uk/presentations/dlj-gr-passwords2016.pdf&ved=0ahUKEwjZntKh9pDVAhUqLcAKHZs2Ar0QFggiMAE&usg=AFQjCNEQuO-DdYOuDM5YTUPI2TOIEmtysg

People have proposed changes to the algorithm to make it more secure (especially the use of HMAC-MD5 has proven to be an issue). To be honest I haven't looked to closely into this myself, but since the browser extensions also stopped working properly I have been using Pwdhash less in the last time. I still think the basic idea is good, but it needs an update and better software support again :) I hope I can update this little tool at some point, but currently I lack the time.

**Comment by quassy** [comment]
FYI the [Firefox addon](https://github.com/pwdhash/pwdhash-webextension) is seeing development again and is now a WebExtension which is working fine for me. And there is [PwdHash Sidebar](https://github.com/quassy/pwdhash) (Firefox only) which I started when the old PwdHash addon stopped working ;)

PwdHash certainly has its (security) issues, but I'm not sure if [Cambridge PwdHash](https://www.cl.cam.ac.uk/~dl551/pwdhash/) is worth the switch as PBKDF2 is somewhat prone to bruteforcing as well. As a layman I think a successor should use Argon2 or scrypt.
